package com.utn.jmg.inversiones.model;
// Generated 21-ago-2017 11:21:49 by Hibernate Tools 4.3.1

import java.util.List;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta implements java.io.Serializable, IndicadorEconomico {
	private static final long serialVersionUID = 1L;
	private Long id;
	private String nombre;
	private Double valor;
	private String codigo;

	public Cuenta() {
	}

	public Cuenta(String nombre) {
		this.nombre = nombre;
	}

	public Cuenta(String nombre, Double valor) {
		this.nombre = nombre;
		this.valor = valor;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNombreCuenta() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Double obtenerValor(Empresa empresa, Balance balance, List<Cuenta> cuentas) {
		String nombreBusqueda = this.getNombreCuenta();
		Double valor = balance.buscarCuentaBalanceSinEspacio(nombreBusqueda).getValor();
		Cuenta cuenta = new Cuenta(this.getNombre(), valor);
		cuentas.add(cuenta);
		return valor;
	}

	public String getNombreIndicadorEconomico() {

		return nombre;
	}

	public Boolean sePuedeCalcular(Empresa empresa, Balance balance) throws Exception {

		if (balance.buscarCuentaBalanceSinEspacio(nombre) == null) {
			throw new Exception("No se puede calcular el indicador porque falta la cuenta " + nombre + ".");
		}
		return true;
	}

	@Override
	public String tipoIndicador() {

		return "Cuenta";
	}

	@Override
	public String getNombreIndicadorEconomicoFormateado() {
		return "c_" + nombre;
	}

	public String getNombre() {
		return nombre;
	}

	public Double getValor() {
		return valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

}
