package com.utn.jmg.inversiones.model;
// Generated 21-ago-2017 11:21:49 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Empresa generated by hbm2java
 */
public class Empresa implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private String cuit;
	private String razonSocial;
	private String descripActividad;
	private Date fechaAlta;

	private List<Balance> balances = new ArrayList<Balance>();

	public Empresa() {
	}

	public Empresa(String cuit, String razonSocial, String descripActividad, Date fechaAlta) {
		this.cuit = cuit;
		this.razonSocial = razonSocial;
		this.descripActividad = descripActividad;
		this.fechaAlta = fechaAlta;
	}

	public Empresa(Long id, String cuit, String razonSocial, String descripActividad, Date fechaAlta) {
		this.id = id;
		this.cuit = cuit;
		this.razonSocial = razonSocial;
		this.descripActividad = descripActividad;
		this.fechaAlta = fechaAlta;
	}

	public Empresa(String cuit) {
		this.cuit = cuit;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCuit() {
		return this.cuit;
	}

	public void setCuit(String cuit) {
		this.cuit = cuit;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getDescripActividad() {
		return this.descripActividad;
	}

	public void setDescripActividad(String descripActividad) {
		this.descripActividad = descripActividad;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public void agregarBalance(Balance balance) {
		balances.add(balance);

	}

}
